const bingoItems = {
  sv: [
    {type: 'emoji', content: '🚛', text: 'Lastbil'},
    {type: 'text', content: 'Röd bil'},
    {type: 'emoji', content: '⛽', text: 'Bensinstation'},
    {type: 'text', content: 'Hastighetsskylt'},
    {type: 'emoji', content: '🐄', text: 'Ko'},
    {type: 'text', content: 'Utländsk bilskylt'},
    {type: 'emoji', content: '🌉', text: 'Bro'},
    {type: 'text', content: 'Gul bil'},
    {type: 'emoji', content: '🚁', text: 'Helikopter'},
    {type: 'text', content: 'Vattentorn'},
    {type: 'emoji', content: '🦌', text: 'Rådjur'},
    {type: 'text', content: 'Motorcykel'},
    {type: 'text', content: 'Lada'},
    {type: 'emoji', content: '🏔️', text: 'Berg'},
    {type: 'text', content: 'Kyrka'},
    {type: 'emoji', content: '🚂', text: 'Tåg'},
    {type: 'text', content: 'Vindkraftverk'},
    {type: 'emoji', content: '🎪', text: 'Cirkustält'},
    {type: 'emoji', content: '🏫', text: 'Skola'},
    {type: 'text', content: 'Blå bil'},
    {type: 'emoji', content: '🦅', text: 'Fågel'},
    {type: 'text', content: 'Byggarbetsplats'},
    {type: 'emoji', content: '🌊', text: 'Sjö/Å'},
    {type: 'text', content: 'Husvagn'},
    {type: 'text', content: 'Silo'},
    {type: 'emoji', content: '🌲', text: 'Skog'},
    {type: 'text', content: 'Veteranbil'},
    {type: 'emoji', content: '🐎', text: 'Häst'},
    {type: 'text', content: 'Reklamtavla'},
    {type: 'emoji', content: '🚒', text: 'Brandbil'},
    {type: 'emoji', content: '☁️', text: 'Rolig molnform'},
    {type: 'text', content: 'Traktor'},
    {type: 'emoji', content: '🍟', text: 'McDonald\'s'},
    {type: 'text', content: 'Överkörd djur'},
    {type: 'emoji', content: '🌻', text: 'Solrosfält'},
    {type: 'text', content: 'Vit bil'}
  ],
  en: [
    {type: 'emoji', content: '🚛', text: 'Semi Truck'},
    {type: 'text', content: 'Red Car'},
    {type: 'emoji', content: '⛽', text: 'Gas Station'},
    {type: 'text', content: 'Speed Limit Sign'},
    {type: 'emoji', content: '🐄', text: 'Cow'},
    {type: 'text', content: 'Out-of-State License Plate'},
    {type: 'emoji', content: '🌉', text: 'Bridge'},
    {type: 'text', content: 'Yellow Car'},
    {type: 'emoji', content: '🚁', text: 'Helicopter'},
    {type: 'text', content: 'Water Tower'},
    {type: 'emoji', content: '🦌', text: 'Deer'},
    {type: 'text', content: 'Motorcycle'},
    {type: 'text', content: 'Barn'},
    {type: 'emoji', content: '🏔️', text: 'Mountain'},
    {type: 'text', content: 'Church'},
    {type: 'emoji', content: '🚂', text: 'Train'},
    {type: 'text', content: 'Windmill'},
    {type: 'emoji', content: '🎪', text: 'Circus Tent'},
    {type: 'emoji', content: '🏫', text: 'School'},
    {type: 'text', content: 'Blue Car'},
    {type: 'emoji', content: '🦅', text: 'Bird'},
    {type: 'text', content: 'Construction Zone'},
    {type: 'emoji', content: '🌊', text: 'Lake/River'},
    {type: 'text', content: 'Camping Trailer'},
    {type: 'text', content: 'Silo'},
    {type: 'emoji', content: '🌲', text: 'Forest'},
    {type: 'text', content: 'Antique Car'},
    {type: 'emoji', content: '🐎', text: 'Horse'},
    {type: 'text', content: 'Billboard'},
    {type: 'emoji', content: '🚒', text: 'Fire Truck'},
    {type: 'emoji', content: '☁️', text: 'Funny Cloud Shape'},
    {type: 'text', content: 'Tractor'},
    {type: 'emoji', content: '🍟', text: 'McDonald\'s'},
    {type: 'text', content: 'Road Kill'},
    {type: 'emoji', content: '🌻', text: 'Sunflower Field'},
    {type: 'text', content: 'White Car'}
  ]
};

export default bingoItems;